services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python app/manage.py runserver 0.0.0.0:8000

  ganache:
    build:
      context: .
      dockerfile: docker/Dockerfile.ganache
    ports:
      - "7545:7545"
    volumes:
      - ./contract/build/contracts:/contracts
    command: ganache-cli -h 0.0.0.0 -p 7545 -d